# Generated by Django 2.0.2 on 2018-05-29 16:19

import apps.resource.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixingActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Usuario')),
                ('images', models.ImageField(upload_to=apps.resource.models.FixingActions.url, verbose_name='Imagen de la Accion correctiva')),
                ('time', models.DateField(verbose_name='Fecha de la accion correctiva')),
                ('description', models.TextField(verbose_name='Descripcion de la acción correctiva')),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to=apps.resource.models.Imagen.url, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('existing_use', models.TextField(verbose_name='Uso Actual')),
                ('direction', models.TextField(verbose_name='Localizacion')),
                ('description', models.TextField(verbose_name='Características generales')),
                ('reference_time', models.DateField(verbose_name='Epoca de referencia')),
                ('alternative_of_use', models.TextField(verbose_name='Alternativa de uso')),
                ('other_values', models.TextField(verbose_name='Otros valores')),
                ('outline', models.ImageField(upload_to=apps.resource.models.Resource.url, verbose_name='Croquis')),
                ('image', models.ImageField(upload_to=apps.resource.models.Resource.url_img, verbose_name='Imagen')),
                ('protection_grade', models.SmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], verbose_name='Grado de proteccion')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Local público y privado'), (1, 'Local privado'), (2, 'Local público'), (3, 'Espacio público'), (4, 'Arqueológico')], null=True, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Threats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('type', models.CharField(max_length=200, verbose_name='Tipo')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='imagen',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource', verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='geolocalization',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource', verbose_name='Recurso al que pertenece esta Geolocalización'),
        ),
        migrations.AddField(
            model_name='fixingactions',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource'),
        ),
    ]
