# Generated by Django 2.0.2 on 2018-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ManyToManyField(to='resource.Resource', verbose_name='Recursos que integran un Área')),
            ],
        ),
    ]
