# Generated by Django 2.0.2 on 2018-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
