# Generated by Django 2.0.2 on 2018-05-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Sin especificar'), (1, 'Ing. Civil'), (2, 'Geógrafo'), (3, 'Sociólogo'), (4, 'Demógragfo'), (5, 'Arquitecto')], default=0, null=True, verbose_name='categoría')),
                ('boss', models.BooleanField(default=False, verbose_name='Jefe de proyecto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
